### ISSUE TITLE
Promote this tweet/s from Hatchet everywhere. We need to raise awareness.

### ISSUE THREAD

**Issue by C2daB** [symbol/xymbassadors#19]
![IMG_m37wip](https://user-images.githubusercontent.com/83311961/126074102-07bba2cb-af00-4c6a-a128-ce2f8366aa9f.jpg)

https://twitter.com/0x6861746366574/status/1416513139634364416?s=20

Please also translate to your native language. We need to spread the word everywhere.

**Comment by himel234** [comment]
https://twitter.com/SamiurR76186237/status/1416677506149621760?s=19

**Comment by C2daB** [comment]
https://twitter.com/SymbolBlogRO/status/1416728907550703616?s=19

**Comment by AngelNEM** [comment]
https://twitter.com/bestgoldangel/status/1416518089827618819?s=21

https://twitter.com/bestgoldangel/status/1416720378836234244?s=21

https://twitter.com/nem_russia/status/1416709176227598343?s=21

https://twitter.com/bestgoldangel/status/1416531484966625280?s=21

**Comment by HexagonTR** [comment]
https://twitter.com/Hexagon_tr/status/1416836100862136328?s=20

**Comment by faizulreza** [comment]
https://twitter.com/FaizulReza1/status/1416660213797515266?s=19

**Comment by mxaxnxn** [comment]
https://twitter.com/eikcimickie/status/1416920395328868355?s=20

**Comment by simonm99** [comment]
https://symbolblog.com/social-media/symbol-blockchain-tweet-update-190721/

**Comment by invictusrav** [comment]
https://twitter.com/NemPilipinas/status/1417317363637047300?s=19
https://twitter.com/rav0316/status/1417319444473257990?s=19

**Comment by niaShaa** [comment]
https://twitter.com/Niashabid17/status/1417643270025342978
https://twitter.com/Niashabid17/status/1417642807133577216

**Comment by mxaxnxn** [comment]
Please upvote on reddit: https://www.reddit.com/r/nem/comments/oohgob/read_this_thread_from_hatchet_as_she_shares_her/?utm_source=share&utm_medium=web2x&context=3

**Comment by leoschwab** [comment]
https://twitter.com/schwab_leonardo/status/1417907478419943428

**Comment by Dtbychris** [comment]
https://twitter.com/NEM_Taiwanese/status/1420343930827132933?s=20
https://twitter.com/NEM_Taiwanese/status/1420347098650742784?s=20

**Comment by faizulreza** [comment]
https://twitter.com/FaizulReza1/status/1420412332514037762?s=19

https://twitter.com/FaizulReza1/status/1420413014109417479?s=19

https://twitter.com/FaizulReza1/status/1420413256347254791?s=19

https://twitter.com/FaizulReza1/status/1420413444830810113?s=19

https://twitter.com/FaizulReza1/status/1420413755570081797?s=19
