### ISSUE TITLE
Hummingbot Promotion (XYM Campaign)

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#2]
We should all learn more about it and start increasing our liquidity as a community, rather than relying on others. This is how we empower ourselves. This is a great way for people to contribute to the cause. 

Symbol liquidity mining campaign with HummingBot 
https://hummingbot.io

Symbol weekly rewards will be doubling to XYM 10,000 on KuCoin. 
This campaign will be extending for another 3 months starting July 13th.

You can also check this article on liquidity mining, written by @rigel_nem 
https://michelinux.medium.com/my-first-steps-in-xym-btc-liquidity-mining-fc290555e4c1

**Comment by C2daB** [comment]
https://twitter.com/DjCellBlock/status/1416757008406024193?s=19

**Comment by faizulreza** [comment]
https://twitter.com/FaizulReza1/status/1416867286741176322?s=19

**Comment by invictusrav** [comment]
https://twitter.com/NemPilipinas/status/1416936045245911040?s=20

**Comment by invictusrav** [comment]
https://twitter.com/rav0316/status/1416934329234587649?s=20

**Comment by HexagonTR** [comment]
https://twitter.com/Hexagon_tr/status/1417099104598077443?s=20

**Comment by leoschwab** [comment]
https://twitter.com/schwab_leonardo/status/1417906965896962048
