### ISSUE TITLE
Community Branding Sentiment

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#20]
https://docs.google.com/forms/d/10GkORjXHlLsDetneds4Xt3iZfumWh2dAZtgwZxwbsRU/edit?usp=sharing

Please request edit access and help by creating new questions with multiple choice answers. 
We can also add a custom banner.

Once we have completed an English version, we can have translated editions made.

Don't forget to self-assign this "issue" to yourself here on github!

**Comment by psputnik** [comment]
Once the poll is ready, I can make the charts for the presentation.
Question: Is it going to be an audio LIVE townhall?

**Comment by psputnik** [comment]
SPAnish Poll Version:
https://docs.google.com/forms/d/1La77hviN7gXNwcw3VFvhiFMHj3uGs4QhKfgJzVvMgcw/edit

**Comment by leoinker** [comment]
> SPAnish Poll Version:
> https://docs.google.com/forms/d/1La77hviN7gXNwcw3VFvhiFMHj3uGs4QhKfgJzVvMgcw/edit

Please drop the Spanish version on this Translation task: https://github.com/symbol/xymbassadors/issues/21
