### ISSUE TITLE
Translate the Community Sentiment questionaire

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#21]
Please make a copy of this form, then edit the questions with translations to your language.
Push your translated copy of the questionnaire to your community. 

https://github.com/symbol/xymbassadors/projects/1#card-65220250

Please do not edit this original copy, but make a new copy first, as demonstrated in this screenshot:

![image](https://user-images.githubusercontent.com/78247431/126251259-60b5aafe-6708-4710-b45c-d07fae5ff3ef.png)

**Comment by himel234** [comment]
Bangla translation:
https://docs.google.com/forms/d/1CxVnR54cZdefejGv6o8dT7V1Fw5u0LV-_j8YJzUIdgY/edit?usp=drivesdk

**Comment by alediemmee** [comment]
Italian translation:
https://forms.gle/jSyp23TLkX6ptb1f8

**Comment by Radio-Radio** [comment]
Japanese one
https://docs.google.com/forms/d/181wzb5MSRkKUfR0CQMCSR-OoCdC7dud3SlWyQBcN_No/edit?usp=sharing

**Comment by psputnik** [comment]
This is the proposed KV, in english. We´re not making it in the different languages, so far. We´ll rely on the Tweet copy.
![SBC_Prop 01](https://user-images.githubusercontent.com/36765087/126327641-70c3368c-997f-4401-8767-7474f29aaf3c.png)

**Comment by psputnik** [comment]
This is the proposed KV, in english. We´re not making it in the different languages, so far. We´ll rely on the Tweet copy.

![SBC_Prop 01](https://user-images.githubusercontent.com/36765087/126327978-bd2cec02-d8d8-4887-af6f-29f6ebf866c0.png)

**Comment by Oldskull82** [comment]
https://t.co/KeLPVYWPlA?amp=1

**Comment by niaShaa** [comment]
Indonesian https://forms.gle/2soFvJjp8NxBiQVb6

**Comment by Dtbychris** [comment]
Chinese
https://t.co/0kiCMBiByt?amp=1

**Comment by invictusrav** [comment]
https://bit.ly/3zekNEU


https://docs.google.com/forms/d/1jvK8YD1uYxlgqgw-q013mDQKwzR8fBOX_C8wpn7Hktg/edit?usp=drivesdk

**Comment by klimgeran** [comment]
🇷🇺Russian: 

https://forms.gle/Cue3APuqXGiL8Bc68

**Comment by leoschwab** [comment]
Portuguese:

https://forms.gle/GtcuimmG2EZaZVYa9

**Comment by HexagonTR** [comment]
Turkish:

https://docs.google.com/forms/d/1q25OQbbB0j0UqExyBL2FKyoj4Tcck9cMic3JhnZFY0U/edit?usp=sharing

**Comment by himel234** [comment]
Sorry i forget to submit Hindi translation

https://docs.google.com/forms/d/1EWjMkCIwnm7gE1aWogqpOFq-P1TDa4E6kNYoxsvbMC8/edit?usp=drivesdk
