### ISSUE TITLE
Create a KV and draft a tweet announcing The NEM Show Discord Branding Discussion.

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#23]
Don't actually tweet it yet.
![SBC_Prop 01](https://user-images.githubusercontent.com/36765087/126375212-16208a1c-2d91-409a-9943-ba44a570ce47.png)

**Comment by psputnik** [comment]
TWEET COPY PROPOSAL

Does our ecosystem need a new name?
Is Symbol the right tagline? Or is it NIS1?
Answer this poll (provided link) and join us in our next townhall, next Tuesday July 27 at 1000 UTC, when we´ll transparently discuss this important matter on The NEM Show Discord channel.
This ship needs you!

KV PROPOSAL

[
![SBC_Prop 01](https://user-images.githubusercontent.com/36765087/126347701-32e5bbe0-adba-4a29-b259-b479caf4c99c.png)
](url)

**Comment by leoinker** [comment]
Tweet Draft below the Xs. Character limit hit.
@psputnik if you're good with this copy, I think you can feel free to add your KV and tweet it!

XXXXXXXXXXXXXXXX

You are invited to The NEM Show Townhall

• Tues, July 27th at 10:00 AM UTC
• The NEM Show Channel on our Discord server: https://discord.gg/xymcity
• Discuss the future of #NEM $XEM & #Symbol $XYM branding.
• Please complete this anonymous questionnaire: https://bit.ly/3zk11rE

**Comment by psputnik** [comment]
I´m happy with this copy of your, buddy!
Let me know if you like this KV and we may start to spread:

![SBC_Prop 02](https://user-images.githubusercontent.com/36765087/126394740-2d6ba3bc-864e-4b06-998f-6ece34eca722.png)

**Comment by leoinker** [comment]
Tweet is out. I will close this issue. 
https://twitter.com/NEM_bol/status/1417605056296361984?s=20
