### ISSUE TITLE
Write a community sentiment report.

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#24]
We need to write a community sentiment report referencing the community feedback.

Action Items
* Collect / count forum, and social media comments. 
* Examine consequences experienced by other projects that have rebranded. 
* Create graphic showing side by side comparison of NEM & Symbol branding differences. - Commentary on the implications.
* Infographics - WILL REVISIT

**Comment by Oldskull82** [comment]
All the response so far: 
https://docs.google.com/forms/d/1LwBH9GEq4uq8kjjDzgmCKF_TgIyvKz4Z0RbnyKYatic/edit#responses

**Comment by leoinker** [comment]
> All the response so far:
> https://docs.google.com/forms/d/1LwBH9GEq4uq8kjjDzgmCKF_TgIyvKz4Z0RbnyKYatic/edit#responses

Deleting, as this is the link with edit abilities.

**Comment by Radio-Radio** [comment]
I submitted Japanese translation of "Community Sentiment Report | Branding".

https://github.com/symbol/xymbassadors/blob/05a075d3df2682e7c2993952fe17215b32a3b650/Community%20Sentiment%20Report%20%7C%20BrandingJapanese%20translation%20Symbol%E3%83%96%E3%83%A9%E3%83%B3%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%82%BB%E3%83%B3%E3%83%81%E3%83%A1%E3%83%B3%E3%83%88%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88.md
