### ISSUE TITLE
Push The NEM Show Townhall on our Ecosystem Branding (2nd push)

### ISSUE THREAD

**Issue by psputnik** [symbol/xymbassadors#26]
Translate in your language and retweet this post:
https://twitter.com/NEM_bol/status/1417605056296361984?s=20

KEYPOINT: Remind audience to FILL the questionnaire and JOIN us on Discord

KV:
![SBC_Prop 01 copia](https://user-images.githubusercontent.com/36765087/126401246-8ee1a566-4462-425e-bcc3-5f36644c690e.jpg)

-----------
Proposed KV (Change link to your language):
-----------

Did you complete the branding questionnaire? 
https://t.co/zQP9OJ4yAh?amp=1
Let´s decide the future image of the #NEM Ecosystem!
It´s up to you.
Remember: We´ll be having a live town hall on our Discord server,The NEM Show Channel, this Tuesday,  July 27th at 10:00 AM UTC.
#Symbol $XYM $XEM
![SBC_Prop 01 copia 2](https://user-images.githubusercontent.com/36765087/126640705-11c27dc1-bc69-4603-90fe-e5466c084b15.jpg)

**Comment by faizulreza** [comment]
https://twitter.com/FaizulReza1/status/1417609592687644676?s=19

https://twitter.com/FaizulReza1/status/1417609590510813189?s=19

**Comment by leoinker** [comment]
https://twitter.com/LeonRedinger/status/1417609240131293189?s=20

**Comment by C2daB** [comment]
https://twitter.com/DjCellBlock/status/1417616339754176515?s=19

**Comment by niaShaa** [comment]
https://twitter.com/Niashabid17/status/1417640438744248322

**Comment by Oldskull82** [comment]
https://twitter.com/NemEspanol/status/1417642533451145216
https://twitter.com/NemBasics/status/1417655045756162051
https://twitter.com/todo_nem/status/1417631576058388486
https://twitter.com/NEM_tonic/status/1417654676187762696

**Comment by mxaxnxn** [comment]
https://twitter.com/eikcimickie/status/1417654529122652164?s=20

**Comment by Dtbychris** [comment]
https://twitter.com/NEM_Taiwanese/status/1417681613794676739?s=20

**Comment by Dtbychris** [comment]
https://twitter.com/NEM_Taiwanese/status/1417682283448848385?s=20

**Comment by mikunNEM** [comment]
https://twitter.com/NEM_Japan/status/1417628514971381761?s=20

**Comment by invictusrav** [comment]
https://twitter.com/rav0316/status/1417690440220897284?s=19

**Comment by invictusrav** [comment]
https://twitter.com/NemPilipinas/status/1417689835154804741?s=19

**Comment by himel234** [comment]
https://twitter.com/SamiurR76186237/status/1417663810668691461?s=19

**Comment by klimgeran** [comment]
https://twitter.com/nem_russia/status/1417722560733532161?s=21

**Comment by klimgeran** [comment]
https://twitter.com/nem_russia/status/1417728627714584579?s=21

**Comment by klimgeran** [comment]
https://t.me/NemRussia/570

**Comment by johnnytongki** [comment]
https://twitter.com/tongkijohnny/status/1417736791096848386?s=21

**Comment by AngelNEM** [comment]
https://twitter.com/nem_russia/status/1417728627714584579?s=21

https://twitter.com/bestgoldangel/status/1417739417440202752?s=21

https://twitter.com/bestgoldangel/status/1417749771192868866?s=21

**Comment by simonm99** [comment]
https://symbolblog.com/japan/symbol-blockchain-tweet-update-200721/

**Comment by himel234** [comment]
https://twitter.com/SamiurR76186237/status/1417663810668691461?s=19

**Comment by alediemmee** [comment]
Personal: https://twitter.com/alediemmee/status/1417787298465435654

Nem Italia: https://twitter.com/NemItalia/status/1417780085025820673?s=20

**Comment by faizulreza** [comment]
https://twitter.com/FaizulReza1/status/1417791451816099843?s=19

**Comment by Radio-Radio** [comment]
https://twitter.com/RadioRa26841511/status/1417817204976852994?s=20

**Comment by itolgacelik** [comment]
https://twitter.com/nemturkey/status/1417790687911849987?s=21

**Comment by leoschwab** [comment]
https://twitter.com/schwab_leonardo/status/1417904741716221960

**Comment by HexagonTR** [comment]
https://twitter.com/Hexagon_tr/status/1417845367715020801?s=20
https://twitter.com/Hexagon_tr/status/1417852645381967876?s=20

**Comment by faizulreza** [comment]
https://twitter.com/FaizulReza1/status/1417791451816099843?s=07

**Comment by psputnik** [comment]
**Proposed KV (Change link to your language):**
--------------------------
![SBC_Prop 01 copia 2](https://user-images.githubusercontent.com/36765087/126640362-65d2cd53-cd5e-4beb-aeac-cc5320b1a3f1.jpg)

Did you complete the branding questionnaire? 
https://t.co/zQP9OJ4yAh?amp=1
Let´s decide the future image of the #NEM Ecosystem!
It´s up to you.
Remember: We´ll be having a live town hall on our Discord server,The NEM Show Channel, this Tuesday,  July 27th at 10:00 AM UTC.
#Symbol $XYM $XEM

**Comment by faizulreza** [comment]
This is my language and tweet is posted by Samiur so I just retweet it.
 https://twitter.com/SamiurR76186237/status/1417663810668691461?s=19

**Comment by C2daB** [comment]
https://twitter.com/DjCellBlock/status/1418225112629727238?s=19

**Comment by Dtbychris** [comment]
https://twitter.com/NEM_Taiwanese/status/1418226155283357703?s=20

**Comment by alediemmee** [comment]
https://twitter.com/alediemmee/status/1418233684457672706?s=20

**Comment by anamoura-29** [comment]
https://twitter.com/AnaPikachu912/status/1418622933254217733
https://twitter.com/AnaPikachu912/status/1418489587022942211

**Comment by faizulreza** [comment]
https://twitter.com/FaizulReza1/status/1418934765709836288?s=19

**Comment by johnnytongki** [comment]
https://t.me/NemRussia/573
