### ISSUE TITLE
Register on Hackmd

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#31]
Register with your github account, then edit your profile to set your username the same as it is on github. 

Make sure to click "Save" on settings so that the username applies. 
Please comment once you have completed this, and I can add you to the Xymbassadors team on hackmd. 

Register here: https://hackmd.io/

**Comment by invictusrav** [comment]
invictusrav

@SO8oKBjaTj6HJfJ97eWEAg

**Comment by simonm99** [comment]
simonm99
@urM9w7NlSkKiQNgiOp9z6Q

**Comment by klimgeran** [comment]
https://hackmd.io/@klimgeran

**Comment by mikunNEM** [comment]
https://hackmd.io/@mikunNEM

**Comment by faizulreza** [comment]
https://hackmd.io/@faizulreza

**Comment by kyle97119** [comment]
https://hackmd.io/@kyle97119

**Comment by C2daB** [comment]
https://hackmd.io/@c2dab

**Comment by himel234** [comment]
https://hackmd.io/@samiur

**Comment by psputnik** [comment]
https://hackmd.io/@psputnik

**Comment by itolgacelik** [comment]
https://hackmd.io/@dFNKXi3FTPi54P1Tg2tIhQ

**Comment by alediemmee** [comment]
https://hackmd.io/@alediemmee

**Comment by HexagonTR** [comment]
https://hackmd.io/@OK5zmS8FRWy0gK9PPkY_ZA

**Comment by johnnytongki** [comment]
https://hackmd.io/@johnnytongki77

**Comment by AngelNEM** [comment]
https://hackmd.io/@angelnem001

**Comment by anamoura-29** [comment]
https://hackmd.io/@anamoura-29

**Comment by leoschwab** [comment]
https://hackmd.io/@kZIFrZbDTRWRUCyg16y50A

**Comment by Oldskull82** [comment]
https://hackmd.io/@Oldskull1982

**Comment by Dtbychris** [comment]
https://hackmd.io/@DragonChris

**Comment by mxaxnxn** [comment]
I finally got my github account back.

https://hackmd.io/@mxaxnxn

**Comment by Radio-Radio** [comment]
https://hackmd.io/@Radio-Radio

**Comment by simonm99** [comment]
I updated my username:

https://hackmd.io/@XHarvesting
