### ISSUE TITLE
Document Existing Brand Expression by 3rd Parties

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#32]
Collect screenshots to document the manner of expression of the NEM & Symbol brands as displayed on exchanges, staking services, and anywhere XEM and XYM are integration.

Please paste the screenshots directly into this file. 
https://github.com/symbol/xymbassadors/blob/main/BrandSentiment/3rdPartyBrandExpression.md

**Comment by Oldskull82** [comment]
POLONIEX: 
XYM: SYMBOL
XEM: NEM
![Screenshot_20210723-173225_Chrome](https://user-images.githubusercontent.com/87346219/126843922-06eb0357-33c5-4c4d-a01f-8e7e6e94d7f5.jpg)
![Screenshot_20210723-173311_Chrome](https://user-images.githubusercontent.com/87346219/126843924-32634019-0b3c-4926-a827-30a2f1571e44.jpg)

**Comment by faizulreza** [comment]
CoinMarketCap 

Xym view here

![IMG_20210724_034227.jpg](https://user-images.githubusercontent.com/87613212/126844523-e82c149d-0aab-4e14-b766-c1aaacb63cae.jpg)

**Comment by alediemmee** [comment]
Coingecko:
NEM : XEM
SYMBOL : XYM 


![Screenshot_127](https://user-images.githubusercontent.com/44278487/126845261-4664b28b-f95c-4871-825a-8e74e81ba035.png)
![Screenshot_129](https://user-images.githubusercontent.com/44278487/126845306-a1bcaa95-52fe-43e7-aa17-1cec25752d6b.png)

**Comment by faizulreza** [comment]
CoinMarketCap view ![IMG_20210724_034227.jpg](https://user-images.githubusercontent.com/87613212/126846112-41dbd7e4-235b-484e-b63a-0064e85ed908.jpg)

**Comment by faizulreza** [comment]
KuCoin View 

Symbol: XYM (BTC/USDT)

Nem: Xem (BTC/USDT)

Including Information. 

![Screenshot_2021-07-24-03-48-51-898_com.kubi.kucoin.jpg](https://user-images.githubusercontent.com/87613212/126846400-4ce9a36f-0d2d-4056-90c7-d8f8bd71f208.jpg)

![Screenshot_2021-07-24-03-49-02-365_com.kubi.kucoin.jpg](https://user-images.githubusercontent.com/87613212/126846411-1d28a3be-eadf-4562-9306-aeb9743d67c0.jpg)

![Screenshot_2021-07-24-03-49-38-215_com.kubi.kucoin.jpg](https://user-images.githubusercontent.com/87613212/126846430-5e041453-84df-429c-a564-a45e7bafd468.jpg)

![Screenshot_2021-07-24-03-49-48-100_com.kubi.kucoin.jpg](https://user-images.githubusercontent.com/87613212/126846440-b70ae95f-9b36-4c22-89ae-ed64f2ae0aff.jpg)

![Screenshot_2021-07-24-04-06-50-219_com.kubi.kucoin.jpg](https://user-images.githubusercontent.com/87613212/126846448-8c0eff2d-8db3-4a1f-ad82-1b8820504880.jpg)

![Screenshot_2021-07-24-04-07-00-734_com.kubi.kucoin.jpg](https://user-images.githubusercontent.com/87613212/126846454-40ced131-f991-4e02-bd58-b31fd72bd476.jpg)

**Comment by niaShaa** [comment]
Probit Exchanges

XEM
![image](https://user-images.githubusercontent.com/87531141/126852823-211f52aa-74a8-478f-bcc4-2ffeed0e3096.png)

XYM

![image](https://user-images.githubusercontent.com/87531141/126852851-2de0c1a5-f0cd-415d-8533-8a545ad63929.png)

**Comment by niaShaa** [comment]
Indodax ( Indonesian Exchange)
XEM/IDR

![image](https://user-images.githubusercontent.com/87531141/126852918-0807c770-d075-4e02-9fb9-1523e201d2c2.png)

**Comment by mikunNEM** [comment]
Zaif exchange

<img width="1314" alt="スクリーンショット 2021-07-24 11 41 36" src="https://user-images.githubusercontent.com/45915246/126855348-430c96fe-1bf6-484f-aaea-322a3444a0c1.png">
<img width="1320" alt="スクリーンショット 2021-07-24 11 41 23" src="https://user-images.githubusercontent.com/45915246/126855351-b8ffa270-716f-450f-8744-0a2f9a58b837.png">

**Comment by C2daB** [comment]
![Screenshot_20210724_052047](https://user-images.githubusercontent.com/83311961/126855978-0350090c-7d3f-4a13-bcf8-576f9e496180.jpg)
![Screenshot_20210724_052020](https://user-images.githubusercontent.com/83311961/126855983-4eb3e055-5b7c-4bf8-9646-5b1542372000.jpg)

**Comment by anamoura-29** [comment]
![Screenshot 2021-07-25 at 8 46 47 AM](https://user-images.githubusercontent.com/60952787/126889111-cd3cec10-f8c9-4f4b-a0ca-1fafe823862e.png)
