### ISSUE TITLE
Collect NEM Forum Sentiment.

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#33]
Primarily from these forum threads: <will add links later>

**Comment by Dtbychris** [comment]
NEM Forum Has basically become a place to discuss prices
This is very serious, see if there is any way to prevent this problem
Or stop using the NEM forum. This is my idea, reference
It seems that only the price has a more enthusiastic response
Other topics, low participation
Unless there is a major announcement
Now NEM guys are basically looking for answers on Twitter

https://forum.nem.io/t/symbol-xym-price-charts/27876?u=dtbychris
https://forum.nem.io/t/nem-xem-price-charts/1204/1582?u=dtbychris
