### ISSUE TITLE
Write regional sentiment report

### ISSUE THREAD

**Issue by leoinker** [symbol/xymbassadors#34]
Each XYMbassador should write a brief summary of the state of affairs in their community, as it pertains to branding.

A couple paragraphs is suitable to explain the current prevailing opinions and concerns in the community.

Please see the submission below, as submitted by @psputnik It is a great example!

**Comment by psputnik** [comment]
Spanish version, done:
[https://github.com/symbol/xymbassadors/blob/main/Community%20Sentiment%20Report_%20SPA%20Community](url)

**Comment by Dtbychris** [comment]
Chinese version
https://gist.github.com/Dtbychris/053fd63bd056f180ad19f7cd89616bc9

**Comment by leoinker** [comment]
> Chinese version
> https://gist.github.com/Dtbychris/053fd63bd056f180ad19f7cd89616bc9

Can you put this on hackmd or the xymbassadors repo?

**Comment by alediemmee** [comment]
Italian: https://gist.github.com/alediemmee/8e6b0115152b6748b4c2b8d2a62c539c
Comments: (Alexis, I used your template :D )

**Comment by klimgeran** [comment]
🇷🇺 Russian:

https://github.com/symbol/xymbassadors/blob/main/Community_Sentiment_Report_Russian_Community.md

**Comment by Oldskull82** [comment]
A short feedback from telegram channels: https://gist.github.com/Oldskull82/f1715dba94d8c7e339c60971cd628f46

**Comment by HexagonTR** [comment]
Turkish Done, Thank you @psputnik for the template :)

https://github.com/symbol/xymbassadors/blob/main/Community_sentiment_Report_Turkish

**Comment by Radio-Radio** [comment]
I updated Japanese sentiment report.

https://hackmd.io/@xymbassador/S1qQqD9C_

Can I publish this as a progress report?
Or do you want to wait until after the voting is closed?

**Comment by himel234** [comment]
https://github.com/symbol/xymbassadors/commit/4da35ce6539efefa2960676425552c1456829ec3

**Comment by leoschwab** [comment]
@leoinker please, how to write inside github just like psputnik did?

**Comment by Radio-Radio** [comment]
Up dated Japanese Ver. This is final result.


https://github.com/symbol/xymbassadors/blob/a599f4db3d99bd8b406ca320a1e1ab1fa8a7db56/Community%20Sentiment%20Report_%20Japanese%20Community_%20Results.%E3%82%B3%E3%83%9F%E3%83%A5%E3%83%8B%E3%83%86%E3%82%A3%E3%83%AA%E3%83%9D%E3%83%BC%E3%83%88Symbol%20%E3%83%96%E3%83%A9%E3%83%B3%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%83%87%E3%82%A3%E3%82%B9%E3%82%AB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E9%9B%86%E8%A8%88%E7%B5%90%E6%9E%9C.md

**Comment by niaShaa** [comment]
https://hackmd.io/@2AcA7ZxRRTqI9EFEKR2bnQ/rkVgohD0_

**Comment by leoschwab** [comment]
Community_Sentiment_Report_PT-BR
