### ISSUE TITLE
SCAM: Report and Warn people of Grit Network 

### ISSUE THREAD

**Issue by C2daB** [symbol/xymbassadors#41]
_**Symbol's code is being used in malicious activity.**_

**1. Report both of the pages below.**
**2. Share this information with everyone! (Twitter, Telegram, etc...)**

_Let everyone know about this and encourage them to get involved too._

https://support.github.com/contact/report-abuse?category=report-abuse&report=averyriley&report_id=62295527&report_type=user

https://github.com/contact/report-abuse?report=Grit-Network

![gritnetwork report](https://user-images.githubusercontent.com/83311961/127378561-5fb34571-c1a7-41c8-b75e-d28dfa021bd2.png)

**Reasons you can and should use in your detailed report:**

- Immediate fork & private ICO without the proper legal approval
- The form collects user data (first name, last name, phone numbers)
- It encourages people to exchange USD to engage in a new investment
- The user making these forks for his organization, to advertise and solicit money from unsuspecting investors
- Unrealistic development roadmap
- Timelines provided, which are impossible to achieve
- Lack of detail
- Simplistic charts/visual data
- No evidence of their own development activities
- No team profile

**When reporting the pages, make sure you include the below screenshots .** 👇 

![grit_information collect](https://user-images.githubusercontent.com/83311961/127379816-5b0899fb-8741-422a-9c96-27c98938570a.png)
![gritnetwork-repo](https://user-images.githubusercontent.com/83311961/127379819-68777619-031c-494d-8bb8-50128c78e981.png)

**Comment by alediemmee** [comment]
Done 👍

**Comment by 0x6861746366574** [comment]
Will replace this with another issue - this currently looks like brigading, which is against GitHub's ToS.
