### ISSUE TITLE
Secure your account with 2FA on Github/Twitter/Discord and so on.

### ISSUE THREAD

**Issue by alediemmee** [symbol/xymbassadors#42]
2FA is an additional layer of security used to ensure only authenticated users gain access to an online account.
This additional layer will increase the security of your account. 

Please increase the security of your account on GitHub and on other Social Media Platforms.
I also would suggest to not use SMS verification since could be less efficient but instead using an APP (example Authy, Google authenticator) or way better, an 2FA hardware where it's possible like
- Yubikey
- Nitrokey

Here a screenshot to help you to secure your account on GitHub
![2fa GitHub](https://user-images.githubusercontent.com/44278487/127455461-f32db507-5b61-459d-926a-42a5e58edcfc.png)

**Comment by HexagonTR** [comment]
Done.

**Comment by Dtbychris** [comment]
Done

**Comment by niaShaa** [comment]
Done

**Comment by invictusrav** [comment]
Done

**Comment by Radio-Radio** [comment]
Done

**Comment by klimgeran** [comment]
<img width="631" alt="Screen Shot 2021-07-29 at 4 49 27 PM" src="https://user-images.githubusercontent.com/30126937/127462325-4904ec9d-16ca-43b0-a8e9-d4d7b569a085.png">


Done ✅

**Comment by mxaxnxn** [comment]
Done ✅

**Comment by faizulreza** [comment]
Done✅

**Comment by mikunNEM** [comment]
Done✅

**Comment by johnnytongki** [comment]
Done

**Comment by Oldskull82** [comment]
done

**Comment by leoschwab** [comment]
done
