### ISSUE TITLE
Create Reddit Account

### ISSUE THREAD

**Issue by mxaxnxn** [symbol/xymbassadors#43]
Please drop in your Reddit accounts and we'll ask the main admin of r/nem to make you moderators of the subreddit.

**Comment by faizulreza** [comment]
https://www.reddit.com/u/faizul_reza

**Comment by alediemmee** [comment]
https://www.reddit.com/user/alediemmee

**Comment by simonm99** [comment]
https://www.reddit.com/user/XHarvesting (it's a new account)

**Comment by johnnytongki** [comment]
https://www.reddit.com/user/JohnnyTongki/

**Comment by Dtbychris** [comment]
https://www.reddit.com/user/Dtbychris

**Comment by HexagonTR** [comment]
https://www.reddit.com/user/HexagonTR

**Comment by himel234** [comment]
https://www.reddit.com/user/himel234/

**Comment by invictusrav** [comment]
https://www.reddit.com/user/rav0316/

**Comment by mikunNEM** [comment]
https://www.reddit.com/user/mikunNEM

**Comment by kyle97119** [comment]
https://www.reddit.com/user/kyle97119

**Comment by klimgeran** [comment]
https://www.reddit.com/user/klimgeran

**Comment by leoschwab** [comment]
https://www.reddit.com/user/leoschwab

**Comment by mxaxnxn** [comment]
I am closing this issue. There was an internal conversation to not add all CMs as mod in r/nem as per @klimgeran. Thanks all!
